//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BossShopMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BossShopMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {SHOP_ITEM}:
        ///    MenuItem:
        ///    - type:{ITEM_TYPE}
        ///    - amount:1
        ///    - name:&amp;9%material%
        ///    - &apos;lore1:&apos;
        ///    - &apos;lore2:&amp;eClick &amp;2esquerdo &amp;epara comprar &amp;b%reward% &amp;epor &amp;c%price%&amp;e.&apos;
        ///    - &apos;lore3:&amp;eClick &amp;2direito &amp;epara vender &amp;c%price_right% &amp;epor &amp;b%reward_right%&amp;e.&apos;
        ///    - &apos;lore4:&amp;eShift + &amp;2Click direito &amp;epara vender todos.&apos;
        ///    RewardType: ITEM
        ///    Reward:
        ///    - - type:{ITEM_TYPE}
        ///      - amount:1
        ///    PriceType: MONEY
        ///    Price: {BUY_PRICE}
        ///    Message: &apos;&amp;eVocê comprou %reward%! Saldo  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {SHOP_ITEM}:
        ///    MenuItem:
        ///    - type:{ITEM_TYPE}
        ///    - amount:1
        ///    - name:&amp;9%material%
        ///    - &apos;lore1:&apos;
        ///    - &apos;lore2:&amp;eClick &amp;2esquerdo &amp;epara comprar &amp;b%reward% &amp;epor &amp;c%price%&amp;e.&apos;
        ///    - &apos;lore3:&amp;eClick &amp;2direito &amp;epara comprar pack &amp;c%price_right% &amp;epor &amp;b%reward_right%&amp;e.&apos;
        ///    RewardType: ITEM
        ///    Reward:
        ///    - - type:{ITEM_TYPE}
        ///      - amount:1
        ///    PriceType: MONEY
        ///    Price: {BUY_PRICE}
        ///    Message: &apos;&amp;eVocê comprou %reward%! Saldo restante: &amp;c%left%&apos;
        ///    RewardType_right: ITEM
        ///    Rew [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Back:
        ///    MenuItem:
        ///    - lore:&amp;8Voltar para o Menu
        ///    - name:&amp;cBack
        ///    - amount:1
        ///    - type:REDSTONE
        ///    RewardType: SHOP
        ///    Reward: menu
        ///    PriceType: NOTHING
        ///    Message: &apos;&apos;
        ///    ExtraPermission: &apos;&apos;
        ///    InventoryLocation: {PAGE_COUNT}.
        /// </summary>
        internal static string ReturnButton {
            get {
                return ResourceManager.GetString("ReturnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {SHOP_ITEM}:
        ///    MenuItem:
        ///    - type:{ITEM_TYPE}
        ///    - amount:1
        ///    - name:&amp;9%material%
        ///    - &apos;lore1:&apos;
        ///    - &apos;lore2:&amp;eClick &amp;2esquerdo &amp;epara vender &amp;b%reward% &amp;epor &amp;c%price%&amp;e.&apos;
        ///	- &apos;lore3:&amp;eShift + &amp;2Click direito &amp;epara vender todos.&apos;
        ///    RewardType: MONEY
        ///    Reward: {SELL_PRICE}
        ///    PriceType: MONEY
        ///    Price:
        ///	- - type:{ITEM_TYPE}
        ///      - amount:1
        ///    Message: &apos;&amp;eVocê vendeu %price%!  Saldo: &amp;c%balance%&apos;
        ///    RewardType_shift_right: MONEY
        ///    Reward_shift_right: {SELL_PRICE}
        ///    Pri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
    }
}
